"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "../../components/dashboard/AppShell";

type Metrica={cliente_id:string;cliente_nome:string;tipo?:"ecommerce"|"lead"|"visualizacao";investimento?:number;alcance?:number;cliques?:number;impressoes?:number;leads?:number;cpl?:number|null;pedidos?:number;receita?:number;semConta?:boolean;erro?:string};
type Relatorio={id:string;cliente_nome:string;periodo_inicio:string;periodo_fim:string;criado_em:string};
function money(v:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:2}).format(v)}
function num(v:number){return new Intl.NumberFormat("pt-BR").format(v)}
function date(v:string){return new Date(v).toLocaleDateString("pt-BR")}

export default function RelatoriosExecutivoPage(){
 const [metricas,setMetricas]=useState<Metrica[]>([]);const [relatorios,setRelatorios]=useState<Relatorio[]>([]);const [loading,setLoading]=useState(true);const [connected,setConnected]=useState(true);const [updated,setUpdated]=useState<string|null>(null);
 async function load(){setLoading(true);try{const [m,r]=await Promise.all([fetch("/api/relatorios/metricas-semana",{cache:"no-store"}),fetch("/api/relatorios/list",{cache:"no-store"})]);const md=await m.json();const rd=await r.json();setConnected(md?.conectado??false);setMetricas(md?.metricas??[]);setRelatorios(rd?.relatorios??[]);setUpdated(new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}));}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const valid=useMemo(()=>metricas.filter(m=>!m.semConta&&!m.erro),[metricas]);const spend=valid.reduce((s,m)=>s+Number(m.investimento??0),0);const leads=valid.reduce((s,m)=>s+Number(m.leads??0),0);const reach=valid.reduce((s,m)=>s+Number(m.alcance??0),0);const cpl=leads?spend/leads:null;const connectedCount=valid.length;const pending=metricas.filter(m=>m.semConta||m.erro).length;
 const ranking=[...valid].sort((a,b)=>Number(b.investimento??0)-Number(a.investimento??0));const maxSpend=Math.max(1,...ranking.map(m=>Number(m.investimento??0)));
 return <AppShell title="Relatórios" subtitle="Inteligência e entregas da carteira" activeLabel="Relatórios" sidebarStatus={{lastUpdated:updated}} actions={<div className="flex gap-2"><Link href="/relatorios?gerar=1" className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-zinc-200">Gerar relatório</Link><button onClick={()=>void load()} disabled={loading} className="rounded-xl border border-[#D85A30]/30 bg-[#D85A30]/10 px-4 py-2 text-sm text-[#f0a480] disabled:opacity-50">{loading?"Atualizando...":"↻ Atualizar"}</button></div>}>
 <div className="space-y-5">
  <section className="rounded-[28px] border border-white/10 bg-gradient-to-br from-zinc-950 via-zinc-950 to-[#D85A30]/[.07] p-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#D85A30]">Axven Reporting Intelligence</p><h2 className="mt-2 text-2xl font-semibold text-white">Visão consolidada de performance</h2><p className="mt-2 text-sm text-zinc-400">Métricas da semana, cobertura da carteira e histórico de relatórios em uma leitura.</p></section>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Investimento 7 dias",money(spend),`${connectedCount} clientes com dados`],["Leads",num(leads),"Resultados da semana"],["CPL consolidado",cpl==null?"—":money(cpl),"Investimento ÷ leads"],["Alcance",num(reach),"Soma das contas disponíveis"],["Relatórios gerados",num(relatorios.length),`${pending} clientes sem leitura completa`]].map(([l,v,d],i)=><div key={l} className={`rounded-3xl border p-5 ${i===0?"border-[#D85A30]/30 bg-[#D85A30]/10":"border-white/10 bg-zinc-950/80"}`}><p className="text-xs uppercase tracking-[.14em] text-zinc-500">{l}</p><p className="mt-3 text-3xl font-semibold text-white">{v}</p><p className="mt-2 text-xs text-zinc-500">{d}</p></div>)}</section>
  {!connected&&!loading?<section className="rounded-3xl border border-amber-500/20 bg-amber-500/[.06] p-5 text-sm text-amber-200">Nenhuma conexão Meta ativa. <Link href="/integracoes" className="font-semibold underline">Abrir Integrações</Link></section>:null}
  <section className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Performance semanal</p><h3 className="mt-1 text-lg font-semibold text-white">Investimento por cliente</h3><div className="mt-5 space-y-4">{ranking.map(m=><div key={m.cliente_id}><div className="mb-1.5 flex justify-between gap-4 text-sm"><Link href={`/clientes/${m.cliente_id}`} className="truncate text-zinc-200 hover:text-white">{m.cliente_nome}</Link><span className="shrink-0 text-zinc-400">{money(Number(m.investimento??0))}{m.tipo==="lead"?` · ${m.leads??0} leads`:""}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#D85A30]" style={{width:`${Number(m.investimento??0)/maxSpend*100}%`}}/></div></div>)}{!loading&&!ranking.length?<p className="text-sm text-zinc-500">Nenhuma métrica disponível para o período.</p>:null}</div></div>
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Cobertura</p><h3 className="mt-1 text-lg font-semibold text-white">Saúde das integrações</h3><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-emerald-500/[.06] p-4"><p className="text-xs text-zinc-500">Com leitura</p><p className="mt-1 text-2xl font-semibold text-emerald-300">{connectedCount}</p></div><div className="rounded-2xl bg-amber-500/[.06] p-4"><p className="text-xs text-zinc-500">Sem leitura</p><p className="mt-1 text-2xl font-semibold text-amber-300">{pending}</p></div></div><div className="mt-4 space-y-2">{metricas.filter(m=>m.semConta||m.erro).slice(0,6).map(m=><div key={m.cliente_id} className="flex justify-between gap-3 rounded-xl border border-white/[.06] px-3 py-2 text-xs"><span className="truncate text-zinc-300">{m.cliente_nome}</span><span className="text-zinc-500">{m.semConta?"Sem conta Meta":"Erro de leitura"}</span></div>)}</div></div>
  </section>
  <section className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Entregas</p><h3 className="mt-1 text-lg font-semibold text-white">Relatórios recentes</h3></div><Link href="/relatorios" className="text-sm text-[#f0a480]">Ver operação →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{relatorios.slice(0,6).map(r=><Link key={r.id} href={`/relatorios/${r.id}`} className="rounded-2xl border border-white/10 bg-white/[.03] p-4 transition hover:border-[#D85A30]/30"><p className="font-medium text-white">{r.cliente_nome}</p><p className="mt-2 text-xs text-zinc-500">{date(r.periodo_inicio)} → {date(r.periodo_fim)}</p><p className="mt-3 text-xs text-zinc-600">Gerado em {date(r.criado_em)}</p></Link>)}{!loading&&!relatorios.length?<div className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-zinc-500">Nenhum relatório gerado ainda.</div>:null}</div></section>
 </div></AppShell>;
}
