import Link from "next/link";
import { AppShell } from "@/app/components/dashboard/AppShell";
import { supabaseAdmin } from "@/app/lib/supabaseAdmin";

export const dynamic = "force-dynamic";
export const revalidate = 0;

type Row={id:string;titulo:string;tipo:"pessoal"|"call_prospeccao"|"reuniao_cliente";data_hora:string;duracao_minutos:number|null;status:string;leads_comerciais:{nome:string}|{nome:string}[]|null};
function spDateKey(d:Date){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function startToday(){return `${spDateKey(new Date())}T00:00:00-03:00`}
function fmtDate(v:string){return new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo",weekday:"short",day:"2-digit",month:"2-digit"}).format(new Date(v))}
function fmtTime(v:string){return new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}
const labels={pessoal:"Pessoal",call_prospeccao:"Call de prospecção",reuniao_cliente:"Reunião com cliente"};

export default async function AgendaExecutivoPage(){
 const {data}=await supabaseAdmin.from("compromissos").select("id,titulo,tipo,data_hora,duracao_minutos,status,leads_comerciais(nome)").gte("data_hora",startToday()).neq("status","cancelado").order("data_hora",{ascending:true}).limit(100);
 const rows=(data??[]) as unknown as Row[];const today=spDateKey(new Date());const hoje=rows.filter(r=>spDateKey(new Date(r.data_hora))===today);const calls=rows.filter(r=>r.tipo==="call_prospeccao");const reunioes=rows.filter(r=>r.tipo==="reuniao_cliente");const pessoais=rows.filter(r=>r.tipo==="pessoal");const proximos=rows.slice(0,8);
 const byDay=new Map<string,number>();rows.forEach(r=>{const k=spDateKey(new Date(r.data_hora));byDay.set(k,(byDay.get(k)??0)+1)});const dias=[...byDay.entries()].slice(0,7);const max=Math.max(1,...dias.map(([,n])=>n));
 return <AppShell title="Agenda" subtitle="Comando de compromissos e reuniões" activeLabel="Agenda">
  <div className="space-y-5">
   <section className="flex flex-col gap-4 rounded-[28px] border border-white/10 bg-gradient-to-br from-zinc-950 via-zinc-950 to-[#D85A30]/[.07] p-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#D85A30]">Axven Agenda OS</p><h2 className="mt-2 text-2xl font-semibold text-white">Visão executiva da agenda</h2><p className="mt-2 text-sm text-zinc-400">Calls, reuniões e compromissos futuros em uma única leitura.</p></div><Link href="/dashboard/agenda" className="rounded-xl border border-[#D85A30]/30 bg-[#D85A30]/10 px-4 py-2 text-sm font-medium text-[#f0a480]">Abrir calendário completo →</Link></section>
   <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Hoje",hoje.length,"Compromissos no dia"],["Próximos",rows.length,"Agenda futura ativa"],["Calls",calls.length,"Prospecção"],["Reuniões",reunioes.length,"Clientes"],["Pessoais",pessoais.length,"Compromissos pessoais"]].map(([l,v,d],i)=><div key={String(l)} className={`rounded-3xl border p-5 ${i===0?"border-[#D85A30]/30 bg-[#D85A30]/10":"border-white/10 bg-zinc-950/80"}`}><p className="text-xs uppercase tracking-[.14em] text-zinc-500">{l}</p><p className="mt-3 text-3xl font-semibold text-white">{v}</p><p className="mt-2 text-xs text-zinc-500">{d}</p></div>)}</section>
   <section className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
    <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Próximos compromissos</p><h3 className="mt-1 text-lg font-semibold text-white">Linha do tempo</h3></div><span className="text-xs text-zinc-500">Horário de Brasília</span></div><div className="mt-4 space-y-2">{proximos.map(r=>{const lead=Array.isArray(r.leads_comerciais)?r.leads_comerciais[0]?.nome:r.leads_comerciais?.nome;return <div key={r.id} className="grid grid-cols-[70px_1fr_auto] items-center gap-3 rounded-2xl border border-white/[.06] bg-white/[.02] px-4 py-3"><div><p className="text-sm font-semibold text-white">{fmtTime(r.data_hora)}</p><p className="text-[11px] text-zinc-500">{fmtDate(r.data_hora)}</p></div><div className="min-w-0"><p className="truncate text-sm font-medium text-zinc-200">{r.titulo}</p><p className="mt-1 truncate text-xs text-zinc-500">{lead?`${lead} · `:""}{r.duracao_minutos?`${r.duracao_minutos} min`:"Duração —"}</p></div><span className={`rounded-full border px-2.5 py-1 text-[11px] ${r.tipo==="call_prospeccao"?"border-[#D85A30]/30 bg-[#D85A30]/10 text-[#f0a480]":r.tipo==="reuniao_cliente"?"border-indigo-500/20 bg-indigo-500/10 text-indigo-200":"border-white/10 bg-white/5 text-zinc-400"}`}>{labels[r.tipo]}</span></div>})}{!rows.length?<div className="rounded-2xl border border-emerald-500/15 bg-emerald-500/[.05] p-4 text-sm text-emerald-200">Nenhum compromisso futuro cadastrado.</div>:null}</div></div>
    <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Carga da agenda</p><h3 className="mt-1 text-lg font-semibold text-white">Próximos dias</h3><div className="mt-5 space-y-4">{dias.map(([dia,n])=><div key={dia}><div className="mb-1.5 flex justify-between text-sm"><span className="text-zinc-300">{new Date(`${dia}T12:00:00-03:00`).toLocaleDateString("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit"})}</span><span className="text-zinc-500">{n} {n===1?"compromisso":"compromissos"}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#D85A30]" style={{width:`${n/max*100}%`}}/></div></div>)}{!dias.length?<p className="text-sm text-zinc-500">Sem carga futura para exibir.</p>:null}</div></div>
   </section>
   <section className="rounded-3xl border border-white/10 bg-zinc-950/80 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Operação</p><p className="mt-1 text-sm text-zinc-300">Criação, edição, drag-and-drop e calendário mensal continuam preservados.</p></div><Link href="/dashboard/agenda" className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-sm text-zinc-200">Gerenciar agenda →</Link></div></section>
  </div>
 </AppShell>
}