"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AppShell } from "../components/dashboard/AppShell";

type ClienteRow={id:string;nome:string};
type RelatorioRow={id:string;cliente_nome:string;periodo_inicio:string;periodo_fim:string;criado_em:string};
type MetricaCliente={cliente_id:string;cliente_nome:string;tipo?:"ecommerce"|"lead"|"visualizacao";investimento?:number;alcance?:number;cliques?:number;impressoes?:number;frequencia?:number;cpm?:number|null;leads?:number;cpl?:number|null;pedidos?:number;receita?:number;roi?:number|null;semConta?:boolean;erro?:string};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(v);
const date=(v:string)=>new Date(v+"T00:00:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric"});

export default function RelatoriosPage(){
 const[clientes,setClientes]=useState<ClienteRow[]>([]);const[relatorios,setRelatorios]=useState<RelatorioRow[]>([]);const[isModalOpen,setIsModalOpen]=useState(()=>typeof window!=="undefined"&&new URLSearchParams(window.location.search).get("gerar")==="1");const[selectedClienteId,setSelectedClienteId]=useState("");const[periodoInicio,setPeriodoInicio]=useState("");const[periodoFim,setPeriodoFim]=useState("");const[loading,setLoading]=useState(false);const[feedback,setFeedback]=useState<{type:"success"|"error";message:string}|null>(null);const[metricas,setMetricas]=useState<MetricaCliente[]>([]);const[metricasConectado,setMetricasConectado]=useState(true);const[loadingMetricas,setLoadingMetricas]=useState(true);
 const loadRelatorios=async()=>{const response=await fetch("/api/relatorios/list");const{relatorios:data,clientes:clientesData}=await response.json();setRelatorios(data??[]);setClientes(clientesData??[]);if(clientesData?.[0])setSelectedClienteId(clientesData[0].id)};
 useEffect(()=>{loadRelatorios();fetch("/api/relatorios/metricas-semana").then(r=>r.json()).then(p=>{setMetricasConectado(p?.conectado??false);setMetricas(p?.metricas??[])}).finally(()=>setLoadingMetricas(false))},[]);
 const handleGerar=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedClienteId||!periodoInicio||!periodoFim)return;setLoading(true);setFeedback(null);const r=await fetch("/api/relatorios/gerar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cliente_id:selectedClienteId,periodo_inicio:periodoInicio,periodo_fim:periodoFim})});const d=await r.json();setLoading(false);if(!r.ok||d.error){setFeedback({type:"error",message:d.error??"Erro ao gerar relatório."});return}setFeedback({type:"success",message:`Relatório de ${d.relatorio.cliente_nome} gerado com sucesso!`});setIsModalOpen(false);loadRelatorios()};
 const investimento=metricas.reduce((s,m)=>s+(m.investimento??0),0);const leads=metricas.reduce((s,m)=>s+(m.leads??0),0);
 return <AppShell title="Relatórios" subtitle="Performance · entregas e Meta Ads" activeLabel="Relatórios"><div className="space-y-5">
  <section className="rounded-[28px] border border-white/[0.07] bg-gradient-to-br from-[#0d0e13] via-[#0b0c10] to-[#160d0d] p-7 lg:p-8"><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-[#ff7458]">PERFORMANCE</p><div className="mt-3 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-3xl font-semibold tracking-[-0.04em] text-white lg:text-4xl">Resultados que viram decisão.</h2><p className="mt-2 text-sm text-zinc-500">Métricas reais da operação e histórico de entregas por cliente.</p></div><button onClick={()=>setIsModalOpen(true)} className="rounded-xl border border-[#ff5a3c]/30 bg-[#ff5a3c]/10 px-4 py-2.5 text-xs font-semibold text-[#ff8a70]">+ Gerar relatório</button></div></section>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Clientes monitorados" value={metricas.length}/><Kpi label="Investimento · 7 dias" value={money(investimento)}/><Kpi label="Leads · 7 dias" value={leads}/><Kpi label="Relatórios gerados" value={relatorios.length}/></div>
  {!metricasConectado&&!loadingMetricas?<Link href="/integracoes" className="block rounded-2xl border border-amber-500/20 bg-amber-500/[0.06] p-4 text-xs text-amber-300">Meta Ads não conectada · abrir Integrações →</Link>:null}
  <section className="rounded-[24px] border border-white/[0.07] bg-[#0d0e13] p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-zinc-600">ÚLTIMOS 7 DIAS</p><h3 className="mt-1 text-lg font-semibold text-white">Performance por cliente</h3></div><span className="text-[10px] text-zinc-600">{loadingMetricas?"Atualizando...":"Dados reais"}</span></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{metricas.map(m=><div key={m.cliente_id} className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-5"><p className="font-semibold text-white">{m.cliente_nome}</p>{m.semConta?<p className="mt-3 text-xs text-zinc-600">Sem conta de anúncio vinculada.</p>:m.erro?<p className="mt-3 text-xs text-amber-300">{m.erro}</p>:<div className="mt-4 grid grid-cols-2 gap-4"><Mini label="Investimento" value={money(m.investimento??0)}/><Mini label="Alcance" value={new Intl.NumberFormat("pt-BR").format(m.alcance??0)}/>{m.tipo==="ecommerce"?<><Mini label="Pedidos" value={m.pedidos??0}/><Mini label="Receita" value={money(m.receita??0)} accent/></>:m.tipo==="visualizacao"?<><Mini label="Impressões" value={new Intl.NumberFormat("pt-BR").format(m.impressoes??0)}/><Mini label="CPM" value={m.cpm?money(m.cpm):"—"} accent/></>:<><Mini label="Leads" value={m.leads??0}/><Mini label="CPL" value={m.cpl?money(m.cpl):"—"} accent/></>}</div>}</div>)}</div></section>
  {feedback?<div className={`rounded-2xl border px-4 py-3 text-sm ${feedback.type==="success"?"border-emerald-500/20 bg-emerald-500/10 text-emerald-200":"border-rose-500/20 bg-rose-500/10 text-rose-200"}`}>{feedback.message}</div>:null}
  <section className="rounded-[24px] border border-white/[0.07] bg-[#0d0e13] p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-zinc-600">HISTÓRICO</p><h3 className="mt-1 text-lg font-semibold text-white">Relatórios gerados</h3><div className="mt-5 space-y-2">{relatorios.length===0?<div className="rounded-2xl border border-dashed border-white/[0.07] p-6 text-center text-xs text-zinc-600">Nenhum relatório gerado ainda.</div>:relatorios.map(r=><Link key={r.id} href={`/relatorios/${r.id}`} className="flex flex-col gap-2 rounded-2xl border border-white/[0.06] bg-white/[0.02] p-4 transition hover:border-[#ff5a3c]/20 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-semibold text-white">{r.cliente_nome}</p><p className="mt-1 text-xs text-zinc-600">{date(r.periodo_inicio)} → {date(r.periodo_fim)}</p></div><span className="text-xs font-medium text-[#ff8a70]">Abrir relatório →</span></Link>)}</div></section>
  {isModalOpen?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 px-4 backdrop-blur-sm"><form onSubmit={handleGerar} className="w-full max-w-md rounded-[24px] border border-white/[0.08] bg-[#0d0e13] p-6 shadow-2xl"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#ff7458]">NOVA ENTREGA</p><h3 className="mt-2 text-xl font-semibold text-white">Gerar relatório</h3><div className="mt-5 space-y-3"><Field label="Cliente"><select value={selectedClienteId} onChange={e=>setSelectedClienteId(e.target.value)} className="input-v2">{clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></Field><Field label="Data início"><input type="date" value={periodoInicio} onChange={e=>setPeriodoInicio(e.target.value)} className="input-v2"/></Field><Field label="Data fim"><input type="date" value={periodoFim} onChange={e=>setPeriodoFim(e.target.value)} className="input-v2"/></Field></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setIsModalOpen(false)} className="rounded-xl border border-white/[0.08] px-4 py-2 text-xs text-zinc-400">Cancelar</button><button disabled={loading} className="rounded-xl bg-[#ff5a3c] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{loading?"Gerando...":"Confirmar"}</button></div></form></div>:null}
 </div></AppShell>}
function Kpi({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/[0.07] bg-[#0d0e13] p-5"><p className="text-[11px] text-zinc-600">{label}</p><p className="mt-3 text-2xl font-semibold tracking-[-0.03em] text-white">{value}</p></div>}
function Mini({label,value,accent=false}:{label:string;value:string|number;accent?:boolean}){return <div><p className="text-[10px] text-zinc-600">{label}</p><p className={`mt-1 text-sm font-semibold ${accent?"text-emerald-300":"text-zinc-200"}`}>{value}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs text-zinc-500"><span className="mb-1.5 block">{label}</span>{children}</label>}
