"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "../../components/dashboard/AppShell";

type Cliente = { id:string; nome:string; honorarios:number|null; status_pagamento:string; score:number|null; data_fim_contrato:string|null };
type Financeiro = { id:string; cliente_id:string; valor:number; status:string };
type Tarefa = { id:string; titulo:string; prioridade:string; concluido:boolean; cliente_nome?:string|null };

function money(value:number){ return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(value); }
function Metric({label,value,detail,tone="neutral"}:{label:string;value:string;detail?:string;tone?:"neutral"|"gold"|"good"|"warn"}){
 const tones={neutral:"border-white/10 bg-zinc-950/80",gold:"border-[#D85A30]/30 bg-[#D85A30]/10",good:"border-emerald-500/20 bg-emerald-500/[0.06]",warn:"border-amber-500/25 bg-amber-500/[0.07]"};
 return <div className={`rounded-3xl border p-5 ${tones[tone]}`}><p className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-500">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-white">{value}</p>{detail?<p className="mt-2 text-xs text-zinc-500">{detail}</p>:null}</div>;
}
function Donut({percent}:{percent:number}){ const p=Math.max(0,Math.min(100,percent)); return <div className="relative h-28 w-28 shrink-0 rounded-full" style={{background:`conic-gradient(#D85A30 ${p}%, rgba(255,255,255,.08) 0)`}}><div className="absolute inset-[10px] flex items-center justify-center rounded-full bg-[#0a0a0f]"><span className="text-xl font-semibold text-white">{Math.round(p)}%</span></div></div>; }

export default function ExecutiveDashboardPage(){
 const [clientes,setClientes]=useState<Cliente[]>([]); const [financeiro,setFinanceiro]=useState<Financeiro[]>([]); const [tarefas,setTarefas]=useState<Tarefa[]>([]); const [loading,setLoading]=useState(true); const [updatedAt,setUpdatedAt]=useState<string|null>(null);
 async function load(){ setLoading(true); try{ const response=await fetch("/api/dashboard/data",{cache:"no-store"}); const data=await response.json(); setClientes((data.clientes??[]).map((i:Cliente)=>({...i,honorarios:i.honorarios==null?null:Number(i.honorarios)}))); setFinanceiro((data.financeiro??[]).map((i:Financeiro)=>({...i,valor:Number(i.valor??0)}))); setTarefas(data.tarefas??[]); setUpdatedAt(new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})); }finally{setLoading(false);} }
 useEffect(()=>{void load();},[]);
 const ativos=useMemo(()=>clientes.filter(c=>c.status_pagamento!=="cancelado"),[clientes]);
 const mrr=useMemo(()=>ativos.reduce((s,c)=>s+Number(c.honorarios??0),0),[ativos]);
 const recebido=useMemo(()=>financeiro.filter(f=>f.status==="pago").reduce((s,f)=>s+f.valor,0),[financeiro]);
 const emAberto=useMemo(()=>financeiro.filter(f=>f.status!=="pago").reduce((s,f)=>s+f.valor,0),[financeiro]);
 const pendentes=useMemo(()=>tarefas.filter(t=>!t.concluido),[tarefas]); const criticas=useMemo(()=>pendentes.filter(t=>["urgente","alta"].includes(t.prioridade)),[pendentes]);
 const clientesAtencao=useMemo(()=>ativos.filter(c=>c.status_pagamento==="atrasado"||(c.score!=null&&c.score<60)),[ativos]);
 const saudaveis=Math.max(0,ativos.length-clientesAtencao.length); const saudePct=ativos.length?saudaveis/ativos.length*100:0; const recebimentoPct=mrr?Math.min(100,recebido/mrr*100):0;
 const topClientes=useMemo(()=>[...ativos].sort((a,b)=>Number(b.honorarios??0)-Number(a.honorarios??0)).slice(0,5),[ativos]); const maxHonorario=Math.max(1,...topClientes.map(c=>Number(c.honorarios??0)));
 const sinais=clientesAtencao.length+criticas.length;
 return <AppShell title="Dashboard Executivo" subtitle="Comando geral da operação Axven" activeLabel="Dashboard" sidebarStatus={{lastUpdated:updatedAt}} actions={<button onClick={()=>void load()} disabled={loading} className="rounded-2xl border border-[#D85A30]/30 bg-[#D85A30]/10 px-4 py-2 text-sm font-medium text-[#f0a480] disabled:opacity-50">{loading?"Atualizando...":"↻ Atualizar"}</button>}>
 <div className="space-y-5">
  <section className="flex flex-col gap-4 rounded-[28px] border border-white/10 bg-gradient-to-br from-zinc-950 via-zinc-950 to-[#D85A30]/[0.07] p-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#D85A30]">Axven Executive OS</p><h2 className="mt-2 text-2xl font-semibold text-white">Visão executiva da agência</h2><p className="mt-2 text-sm text-zinc-400">Dinheiro, carteira, prioridades e operação em uma única leitura.</p></div><div className="flex flex-wrap gap-2">{[["Clientes","/clientes"],["Financeiro","/financeiro"],["CRM","/pipeline"]].map(([l,h])=><Link key={h} href={h} className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-zinc-200 hover:border-[#D85A30]/30">{l}</Link>)}</div></section>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="MRR ativo" value={money(mrr)} detail={`${ativos.length} clientes ativos`} tone="gold"/><Metric label="Recebido" value={money(recebido)} detail={`${Math.round(recebimentoPct)}% do MRR`} tone="good"/><Metric label="Em aberto" value={money(emAberto)} detail="Registros ainda não pagos" tone={emAberto>0?"warn":"neutral"}/><Metric label="Clientes" value={String(ativos.length)} detail={`${clientesAtencao.length} exigindo atenção`} tone={clientesAtencao.length?"warn":"neutral"}/><Metric label="Tarefas" value={String(pendentes.length)} detail={`${criticas.length} de alta prioridade`} tone={criticas.length?"warn":"neutral"}/></section>
  <section className="grid gap-4 xl:grid-cols-3">
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Saúde da carteira</p><div className="mt-5 flex items-center gap-6"><Donut percent={saudePct}/><div className="space-y-3 text-sm"><div><p className="text-zinc-500">Saudáveis</p><p className="text-xl font-semibold text-white">{saudaveis}</p></div><div><p className="text-zinc-500">Em atenção</p><p className="text-xl font-semibold text-amber-300">{clientesAtencao.length}</p></div></div></div></div>
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Recebimento do MRR</p><div className="mt-5 flex items-center gap-6"><Donut percent={recebimentoPct}/><div><p className="text-sm text-zinc-500">Recebido</p><p className="mt-1 text-xl font-semibold text-emerald-300">{money(recebido)}</p><p className="mt-3 text-sm text-zinc-500">Em aberto</p><p className="mt-1 font-semibold text-amber-300">{money(emAberto)}</p></div></div></div>
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Concentração do MRR</p><div className="mt-5 space-y-3">{topClientes.map(c=><div key={c.id}><div className="mb-1 flex justify-between gap-3 text-xs"><Link href={`/clientes/${c.id}`} className="truncate text-zinc-300 hover:text-white">{c.nome}</Link><span className="text-zinc-500">{money(Number(c.honorarios??0))}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#D85A30]" style={{width:`${Number(c.honorarios??0)/maxHonorario*100}%`}}/></div></div>)}</div></div>
  </section>
  <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Prioridades</p><h3 className="mt-1 text-lg font-semibold text-white">O que exige atenção</h3></div><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-zinc-400">{sinais} sinais</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{clientesAtencao.slice(0,4).map(c=><Link key={c.id} href={`/clientes/${c.id}`} className="rounded-2xl border border-amber-500/15 bg-amber-500/[.05] p-4"><p className="text-sm font-medium text-white">{c.nome}</p><p className="mt-1 text-xs text-zinc-500">{c.status_pagamento==="atrasado"?"Financeiro em atraso":`Score ${c.score??"—"}`}</p></Link>)}{criticas.slice(0,4).map(t=><div key={t.id} className="rounded-2xl border border-rose-500/15 bg-rose-500/[.04] p-4"><p className="text-sm font-medium text-white">{t.titulo}</p><p className="mt-1 text-xs text-zinc-500">{t.cliente_nome||"Operação interna"} · {t.prioridade}</p></div>)}{!loading&&sinais===0?<div className="md:col-span-2 rounded-2xl border border-emerald-500/15 bg-emerald-500/[.05] p-4 text-sm text-emerald-200">Nenhum alerta crítico neste momento.</div>:null}</div></div>
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Operação</p><h3 className="mt-1 text-lg font-semibold text-white">Acesso rápido</h3><div className="mt-4 grid grid-cols-2 gap-2">{[["Clientes 360º","/clientes"],["Financeiro","/financeiro"],["Criativos","/criativos"],["CRM","/pipeline"],["Agenda","/dashboard/agenda"],["Relatórios","/relatorios"]].map(([l,h])=><Link key={h} href={h} className="rounded-xl border border-white/10 bg-white/[.03] px-3 py-3 text-sm text-zinc-300 transition hover:border-[#D85A30]/30 hover:text-white">{l} <span className="float-right text-zinc-600">→</span></Link>)}</div></div>
  </section>
 </div></AppShell>;
}
