"use client";

import { FormEvent, useEffect, useState } from "react";
type ResultState = null | "qualified" | "unqualified" | "error";
const trackingKeys = ["utm_source","utm_medium","utm_campaign","utm_content","utm_term","fbclid","campaign_id","adset_id","ad_id"] as const;

export default function LeadForm() {
  const [sent,setSent]=useState<ResultState>(null); const [sending,setSending]=useState(false); const [tracking,setTracking]=useState<Record<string,string>>({}); const [leadId,setLeadId]=useState<string|null>(null);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const captured:Record<string,string>={};trackingKeys.forEach(k=>{const v=params.get(k);if(v)captured[k]=v});setTracking(captured)},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(sending)return;setSending(true);setSent(null);const data=new FormData(event.currentTarget);const payload=Object.fromEntries(data.entries());try{const response=await fetch("/api/aquisicao/clinicas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,...tracking,origin_url:window.location.href})});if(!response.ok)throw new Error();const result=await response.json();setLeadId(result.id||null);setSent(result.qualified?"qualified":"unqualified")}catch{setSent("error")}finally{setSending(false)}}
  if(sent==="qualified"&&leadId)return <Scheduler leadId={leadId}/>;
  if(sent==="unqualified")return <Result title="Obrigado pelo interesse na Axven." text="Neste momento, nossa Estrutura de Crescimento foi desenhada para operações em uma fase específica de maturidade. Suas informações poderão ser consideradas futuramente para uma solução mais adequada."/>;
  return <>{sent==="error"&&<div className="mt-8 rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-center text-sm text-red-200">Não foi possível enviar agora. Tente novamente em instantes.</div>}<form onSubmit={submit} className="mt-10 space-y-5 rounded-3xl border border-[#2A2A32] bg-[#0B0B0F] p-6 md:p-8">
<Field label="Seu nome"><input name="name" required className="input"/></Field><Field label="Nome da clínica"><input name="clinic" required className="input"/></Field><Field label="WhatsApp"><input name="whatsapp" required inputMode="tel" className="input"/></Field><Field label="Instagram da clínica"><input name="instagram" className="input"/></Field>
<Field label="Faturamento médio mensal"><select name="revenue" required className="input"><option value="">Selecione</option><option value="20">Até R$ 20 mil</option><option value="34">R$ 20 mil a R$ 35 mil</option><option value="60">R$ 35 mil a R$ 60 mil</option><option value="100">R$ 60 mil a R$ 100 mil</option><option value="300">R$ 100 mil a R$ 300 mil</option><option value="301">Acima de R$ 300 mil</option></select></Field>
<Field label="Investimento atual em anúncios"><select name="ads" required className="input"><option value="">Selecione</option><option>Ainda não investimos</option><option>Até R$ 1.500</option><option>R$ 1.500 a R$ 3.000</option><option>R$ 3.000 a R$ 5.000</option><option>R$ 5.000 a R$ 10.000</option><option>Acima de R$ 10.000</option></select></Field>
<Field label="Quem atende os leads?"><select name="sales" required className="input"><option value="">Selecione</option><option>Eu mesmo(a)</option><option>Uma pessoa responsável pelo atendimento</option><option>Temos uma equipe comercial</option><option>Não temos ninguém responsável</option></select></Field>
<Field label="Principal desafio hoje"><select name="challenge" required className="input"><option value="">Selecione</option><option>Gerar mais oportunidades</option><option>Melhorar a qualidade dos leads</option><option>Transformar mais leads em agendamentos</option><option>Melhorar o comparecimento</option><option>Transformar mais agendamentos em vendas</option><option>Identificar onde perdemos oportunidades</option><option>Outro</option></select></Field>
<Field label="Quanto a clínica está preparada para investir mensalmente em aquisição, considerando estratégia, tecnologia e mídia?"><select name="capacity" required className="input"><option value="">Selecione</option><option value="1">Até R$ 1.500</option><option value="2">R$ 1.500 a R$ 2.000</option><option value="3.9">R$ 2.000 a R$ 4.000</option><option value="6">R$ 4.000 a R$ 6.000</option><option value="10">R$ 6.000 a R$ 10.000</option><option value="11">Acima de R$ 10.000</option></select></Field>
<Field label="Quando pretende começar?"><select name="timing" required className="input"><option value="">Selecione</option><option>Agora</option><option>Nos próximos 30 dias</option><option>Entre 1 e 3 meses</option><option>Estou apenas pesquisando</option></select></Field>
<button disabled={sending} className="w-full rounded-xl bg-gradient-to-r from-[#FF6B35] to-[#FF3D57] px-6 py-4 font-semibold text-white disabled:opacity-60">{sending?"Enviando...":"Enviar análise →"}</button></form></>;
}

function Scheduler({leadId}:{leadId:string}){const[slots,setSlots]=useState<string[]>([]);const[loading,setLoading]=useState(true);const[booking,setBooking]=useState<string|null>(null);const[confirmed,setConfirmed]=useState<string|null>(null);const[error,setError]=useState("");
useEffect(()=>{fetch("/api/aquisicao/clinicas/agenda").then(r=>r.json()).then(d=>setSlots(d.slots||[])).catch(()=>setError("Não foi possível carregar os horários.")).finally(()=>setLoading(false))},[]);
async function book(inicio:string){setBooking(inicio);setError("");try{const r=await fetch("/api/aquisicao/clinicas/agenda",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leadId,inicio})});if(!r.ok)throw new Error();setConfirmed(inicio)}catch{setError("Esse horário não está mais disponível. Escolha outro horário.");const r=await fetch("/api/aquisicao/clinicas/agenda");const d=await r.json();setSlots(d.slots||[])}finally{setBooking(null)}}
if(confirmed){const d=new Date(confirmed);return <Result title="Análise de Crescimento agendada." text={`Seu horário foi reservado para ${d.toLocaleDateString("pt-BR",{timeZone:"America/Sao_Paulo",weekday:"long",day:"2-digit",month:"2-digit"})} às ${d.toLocaleTimeString("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit"})}.`}/>}
const groups=slots.reduce<Record<string,string[]>>((a,s)=>{const k=new Date(s).toLocaleDateString("pt-BR",{timeZone:"America/Sao_Paulo",weekday:"short",day:"2-digit",month:"2-digit"});(a[k]??=[]).push(s);return a},{});
return <div className="mt-10 rounded-3xl border border-[#2A2A32] bg-[#0B0B0F] p-6 md:p-8"><div className="text-center"><div className="mx-auto mb-5 h-2 w-16 rounded-full bg-gradient-to-r from-[#FF6B35] to-[#FF3D57]"/><h3 className="text-2xl font-semibold">Sua clínica tem perfil para avançar.</h3><p className="mt-3 text-[#9B9BA4]">Escolha um horário para sua Análise de Crescimento Axven. Duração: 45 minutos.</p></div>{loading&&<p className="mt-8 text-center text-[#9B9BA4]">Carregando horários...</p>}{error&&<p className="mt-6 text-center text-sm text-red-300">{error}</p>}<div className="mt-8 space-y-6">{Object.entries(groups).map(([day,items])=><div key={day}><p className="mb-3 font-medium capitalize text-[#F5F5F7]">{day}</p><div className="grid grid-cols-3 gap-3 md:grid-cols-6">{items.map(s=><button key={s} disabled={!!booking} onClick={()=>book(s)} className="rounded-xl border border-[#34343D] px-3 py-3 text-sm hover:border-[#FF6B35] hover:bg-[#FF6B35]/10 disabled:opacity-50">{booking===s?"...":new Date(s).toLocaleTimeString("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit"})}</button>)}</div></div>)}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-medium text-[#F5F5F7]">{label}</span>{children}</label>}
function Result({title,text}:{title:string;text:string}){return <div className="mt-10 rounded-3xl border border-[#2A2A32] bg-[#0B0B0F] p-8 text-center"><div className="mx-auto mb-5 h-2 w-16 rounded-full bg-gradient-to-r from-[#FF6B35] to-[#FF3D57]"/><h3 className="text-2xl font-semibold">{title}</h3><p className="mx-auto mt-4 max-w-xl leading-7 text-[#9B9BA4]">{text}</p></div>}
