"use client";

import LeadForm from "./LeadForm";

const steps = [
  ["01", "Atração", "Estratégia, campanhas e criativos para gerar novas oportunidades para sua clínica."],
  ["02", "Lead", "Os novos contatos entram em uma jornada estruturada, com origem e contexto preservados."],
  ["03", "Qualificação", "Organizamos as oportunidades para facilitar a priorização comercial."],
  ["04", "Agendamento", "Acompanhamos a evolução do lead até o agendamento e os próximos passos."],
  ["05", "CRM", "Cada oportunidade passa a ter estágio e histórico dentro do processo comercial."],
  ["06", "Venda + Dados", "Resultados comerciais alimentam a leitura de performance e as próximas decisões."],
];
const fit = ["Fatura a partir de R$ 35 mil por mês","Já possui procedimentos e ofertas validados","Já vende e possui uma operação em funcionamento","Possui alguém responsável pelo atendimento dos leads","Tem capacidade para receber novos pacientes","Está disposta a acompanhar agendamentos e vendas"];

export default function ClinicasPage() {
  return <main className="min-h-screen bg-[#0B0B0F] text-[#F5F5F7]">
    <section className="mx-auto max-w-7xl px-6 pb-16 pt-16 md:pt-24">
      <div className="grid items-center gap-10 lg:grid-cols-[.88fr_1.12fr]">
        <div className="relative z-20">
          <div className="mb-7 inline-flex rounded-full border border-[#34343D] bg-[#111117]/80 px-4 py-2 text-xs font-semibold uppercase tracking-[0.18em] text-[#FF6B35]">Para clínicas de estética com operação validada</div>
          <h1 className="text-5xl font-semibold leading-[1.02] tracking-[-0.045em] md:text-7xl">Transforme seu marketing em uma <span className="bg-gradient-to-r from-[#FF6B35] to-[#FF3D57] bg-clip-text text-transparent">estrutura de aquisição de pacientes.</span></h1>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-[#A4A4AD]">A Axven conecta estratégia, anúncios, atendimento e dados para sua clínica gerar novas oportunidades e acompanhar o que acontece do primeiro contato até a venda.</p>
          <div className="mt-7 grid gap-3 text-sm text-[#C8C8CE] sm:grid-cols-3"><span>◎ Aquisição estruturada</span><span>↗ Jornada acompanhada</span><span>◇ Decisões com dados</span></div>
          <a href="#analise" className="mt-9 inline-flex rounded-xl bg-gradient-to-r from-[#FF6B35] to-[#FF3D57] px-7 py-4 font-semibold text-white shadow-[0_12px_40px_rgba(255,75,65,.18)]">Quero uma análise da minha clínica →</a>
          <p className="mt-4 text-sm text-[#686872]">Para clínicas com faturamento a partir de R$ 35 mil/mês.</p>
        </div>
        <div className="relative min-h-[560px] overflow-hidden rounded-[30px] border border-[#35343A] bg-[#15120F] shadow-2xl">
          <img src="/clinicas/hero-clinica-premium.jpg" alt="Clínica de estética premium com recepção iluminada e sala de procedimento" className="absolute inset-0 h-full w-full object-cover object-center" />
          <div className="absolute inset-0 bg-gradient-to-r from-[#0B0B0F]/30 via-transparent to-[#0B0B0F]/25"/><div className="absolute inset-x-0 bottom-0 h-36 bg-gradient-to-t from-[#0B0B0F]/80 to-transparent"/>
          <div className="absolute left-5 top-5 rounded-full border border-white/15 bg-black/55 px-4 py-2 text-[11px] font-semibold uppercase tracking-[.14em] text-[#FFD0BF] backdrop-blur-md">Clínica de estética • operação premium</div>
          <div className="absolute bottom-5 right-5 top-20 z-10 flex w-[47%] flex-col justify-center gap-3">
            {[["Lead recebido","Instagram Ads","● Agora"],["Agendamento confirmado","WhatsApp","● Próximo passo"],["Oportunidade qualificada","CRM Axven","● Em acompanhamento"],["Venda registrada","Resultado comercial","● Dado da operação"]].map(([t,s,m])=><div key={t} className="rounded-2xl border border-white/10 bg-[#0B0B0F]/88 p-4 shadow-xl backdrop-blur-md"><p className="text-sm font-semibold text-white">{t}</p><p className="mt-1 text-xs text-[#B5B5BD]">{s}</p><p className="mt-2 text-[11px] text-[#70D99A]">{m}</p></div>)}
          </div>
        </div>
      </div>
      <div className="mt-12 grid gap-3 rounded-2xl border border-[#2A2A32] bg-[#111117] p-5 text-center text-xs font-semibold uppercase tracking-[0.12em] text-[#9B9BA4] sm:grid-cols-5"><span>Estratégia</span><span>Mídia paga</span><span>Automação</span><span>CRM & vendas</span><span>Dados & performance</span></div>
    </section>
    <section className="border-y border-[#2A2A32] bg-[#111117]"><div className="mx-auto max-w-6xl px-6 py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#FF6B35]">O gargalo</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold tracking-tight md:text-5xl">O problema pode não estar apenas nos seus anúncios.</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-[#9B9BA4]">Contatos chegam, alguns agendam, outros somem, alguns comparecem e outros compram. No final do mês, sua clínica consegue identificar quais campanhas trouxeram as melhores oportunidades, quantas agendaram e quanto virou venda?</p><div className="mt-10 grid gap-3 md:grid-cols-2">{["Quais anúncios trouxeram as melhores oportunidades?","Quantos leads realmente agendaram?","Quantos compareceram?","Quantos compraram e quanto geraram em vendas?"].map(x=><div key={x} className="rounded-2xl border border-[#2A2A32] bg-[#17171D] p-5">{x}</div>)}</div></div></section>
    <section className="mx-auto max-w-6xl px-6 py-24"><div className="grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-[460px] overflow-hidden rounded-[28px] border border-[#2A2A32] bg-[#111117] shadow-2xl"><img src="https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&fm=jpg&q=84&w=1600" alt="Profissional de estética atendendo paciente em clínica premium" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#0B0B0F]/90 via-transparent to-[#0B0B0F]/10"/><div className="absolute bottom-0 left-0 right-0 p-6 md:p-8"><div className="inline-flex rounded-full border border-white/10 bg-black/45 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.14em] text-[#FF8A64] backdrop-blur-md">Contexto real de operação</div><p className="mt-4 max-w-md text-lg font-medium leading-7 text-white">A experiência da paciente acontece na clínica. A Axven organiza o caminho que traz a oportunidade até ela.</p></div></div><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#FF6B35]">Estrutura de Crescimento Axven</p><h2 className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">Do anúncio ao procedimento vendido.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-[#9B9BA4]">Marketing e comercial passam a fazer parte da mesma leitura operacional.</p><div className="mt-10 grid gap-4 sm:grid-cols-2">{steps.map(([n,t,d])=><article key={n} className="rounded-2xl border border-[#2A2A32] bg-[#111117] p-5"><span className="text-sm font-semibold text-[#FF5A3C]">{n}</span><h3 className="mt-3 text-lg font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-[#9B9BA4]">{d}</p></article>)}</div><div className="mt-6 rounded-2xl border border-[#2A2A32] p-5 text-center text-sm text-[#9B9BA4]">Anúncio → Lead → Qualificação → Agendamento → Venda → Receita → Dados</div></div></div></section>
    <section className="bg-[#111117]"><div className="mx-auto grid max-w-6xl gap-12 px-6 py-24 md:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#FF6B35]">Perfil ideal</p><h2 className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">A Axven não é para toda clínica.</h2><p className="mt-6 leading-8 text-[#9B9BA4]">Foi desenhada para operações que já provaram que conseguem vender e agora querem estruturar aquisição, processo comercial e dados.</p></div><div className="space-y-3">{fit.map(x=><div key={x} className="rounded-xl border border-[#2A2A32] bg-[#17171D] p-4"><span className="mr-3 text-[#FF6B35]">✓</span>{x}</div>)}</div></div></section>
    <section className="mx-auto max-w-6xl px-6 py-24"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#FF6B35]">O que construímos</p><h2 className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">Uma operação conectada, não apenas campanhas.</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{[["Estratégia de aquisição","Campanhas, ofertas e jornadas para geração de demanda."],["Gestão de mídia","Estruturação, operação e otimização das campanhas."],["Criativos de performance","Estratégia, copy, roteiros, design e adaptação dos materiais usados nas campanhas."],["CRM e processo comercial","Organização da jornada entre lead, qualificação, agendamento e venda."],["Tracking e dados","Estrutura para conectar origem, oportunidade e resultado comercial."],["Automações essenciais","Automatizações necessárias dentro do processo padronizado da Axven."]].map(([t,d])=><div key={t} className="rounded-2xl border border-[#2A2A32] bg-[#111117] p-6"><h3 className="text-xl font-semibold">{t}</h3><p className="mt-3 leading-7 text-[#9B9BA4]">{d}</p></div>)}</div></section>
    <section id="analise" className="border-t border-[#2A2A32] bg-[#111117]"><div className="mx-auto max-w-3xl px-6 py-24"><p className="text-center text-sm font-semibold uppercase tracking-[0.18em] text-[#FF6B35]">Análise de Crescimento Axven</p><h2 className="mt-4 text-center text-3xl font-semibold tracking-tight md:text-5xl">Sua clínica tem perfil para avançar?</h2><p className="mx-auto mt-5 max-w-2xl text-center leading-8 text-[#9B9BA4]">Responda algumas perguntas rápidas. Se houver alinhamento com a estrutura atual da Axven, você poderá avançar para o agendamento da análise.</p><LeadForm /></div></section>
    <style jsx global>{`.input{width:100%;border:1px solid #2A2A32;background:#17171D;color:#F5F5F7;border-radius:12px;padding:14px 16px;outline:none}.input:focus{border-color:#FF5A3C}`}</style>
  </main>;
}
