import Link from "next/link";
import { AppShell } from "@/app/components/dashboard/AppShell";
import { supabaseAdmin } from "@/app/lib/supabaseAdmin";

export const dynamic="force-dynamic";export const revalidate=0;
function date(v:string|null){return v?new Date(v).toLocaleDateString("pt-BR"):"—"}
export default async function IntegracoesExecutivoPage(){
 const [{data:conexao},{data:clientes},{data:workflows}]=await Promise.all([
  supabaseAdmin.from("integracao_meta").select("meta_user_nome,conectado_em,expires_at").order("conectado_em",{ascending:false}).limit(1).maybeSingle(),
  supabaseAdmin.from("clientes").select("id,nome,status,status_pagamento,meta_account_id").order("nome"),
  supabaseAdmin.from("n8n_workflow_metadata").select("*").limit(100)
 ]);
 const ativos=(clientes??[]).filter(c=>c.status!=="cancelado");const vinculados=ativos.filter(c=>c.meta_account_id);const semMeta=ativos.filter(c=>!c.meta_account_id);const wf=workflows??[];const metaOk=!!conexao;const coverage=ativos.length?Math.round(vinculados.length/ativos.length*100):0;
 return <AppShell title="Integrações" subtitle="Saúde das conexões da operação" activeLabel="Integrações">
 <div className="space-y-5">
  <section className="flex flex-col gap-4 rounded-[28px] border border-white/10 bg-gradient-to-br from-zinc-950 via-zinc-950 to-[#D85A30]/[.07] p-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#D85A30]">Axven Integration Hub</p><h2 className="mt-2 text-2xl font-semibold text-white">Saúde das integrações</h2><p className="mt-2 text-sm text-zinc-400">Meta, contas vinculadas e automações monitoradas em uma única leitura.</p></div><Link href="/integracoes" className="rounded-xl border border-[#D85A30]/30 bg-[#D85A30]/10 px-4 py-2 text-sm font-medium text-[#f0a480]">Gerenciar integrações →</Link></section>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Meta Ads",metaOk?"Conectada":"Desconectada",metaOk?`Desde ${date(conexao.conectado_em)}`:"Requer conexão"],["Cobertura Meta",`${coverage}%`,`${vinculados.length} de ${ativos.length} clientes`],["Sem conta Meta",String(semMeta.length),"Clientes operacionais ativos"],["Workflows",String(wf.length),"Metadados n8n registrados"],["Clientes ativos",String(ativos.length),"Carteira operacional"]].map(([l,v,d],i)=><div key={l} className={`rounded-3xl border p-5 ${i===0?(metaOk?"border-emerald-500/20 bg-emerald-500/[.06]":"border-rose-500/20 bg-rose-500/[.06]"):i===2&&semMeta.length?"border-amber-500/20 bg-amber-500/[.06]":"border-white/10 bg-zinc-950/80"}`}><p className="text-xs uppercase tracking-[.14em] text-zinc-500">{l}</p><p className="mt-3 text-2xl font-semibold text-white">{v}</p><p className="mt-2 text-xs text-zinc-500">{d}</p></div>)}</section>
  <section className="grid gap-4 xl:grid-cols-[.85fr_1.15fr]">
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Meta Ads</p><h3 className="mt-1 text-lg font-semibold text-white">Conexão principal</h3>{conexao?<div className="mt-5 space-y-3"><div className="rounded-2xl border border-emerald-500/15 bg-emerald-500/[.05] p-4"><p className="text-xs text-zinc-500">Status</p><p className="mt-1 font-semibold text-emerald-300">● Conectada</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/[.03] p-4"><p className="text-xs text-zinc-500">Usuário</p><p className="mt-1 truncate text-sm text-white">{conexao.meta_user_nome??"Conta Meta"}</p></div><div className="rounded-2xl bg-white/[.03] p-4"><p className="text-xs text-zinc-500">Expiração</p><p className="mt-1 text-sm text-white">{date(conexao.expires_at)}</p></div></div></div>:<div className="mt-5 rounded-2xl border border-rose-500/15 bg-rose-500/[.05] p-4 text-sm text-rose-200">Nenhuma conexão Meta ativa.</div>}</div>
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><div className="flex justify-between gap-3"><div><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Cobertura da carteira</p><h3 className="mt-1 text-lg font-semibold text-white">Contas Meta por cliente</h3></div><span className="text-sm text-zinc-500">{coverage}% vinculada</span></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#D85A30]" style={{width:`${coverage}%`}}/></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{ativos.map(c=><Link href={`/clientes/${c.id}`} key={c.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/[.06] px-3 py-2.5 text-sm"><span className="truncate text-zinc-300">{c.nome}</span><span className={c.meta_account_id?"text-emerald-300":"text-amber-300"}>{c.meta_account_id?"Vinculada":"Sem conta"}</span></Link>)}</div></div>
  </section>
  <section className="grid gap-4 xl:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Automações</p><h3 className="mt-1 text-lg font-semibold text-white">n8n monitorado</h3><div className="mt-5 flex items-end justify-between rounded-2xl bg-white/[.03] p-5"><div><p className="text-3xl font-semibold text-white">{wf.length}</p><p className="mt-1 text-xs text-zinc-500">workflows com metadata no hub</p></div><span className={wf.length?"text-emerald-300":"text-zinc-500"}>{wf.length?"● Monitorado":"Sem registros"}</span></div></div><div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Ação</p><h3 className="mt-1 text-lg font-semibold text-white">Pendências de integração</h3><div className="mt-5 space-y-2">{semMeta.slice(0,5).map(c=><div key={c.id} className="flex justify-between rounded-xl border border-amber-500/10 bg-amber-500/[.03] px-3 py-2.5 text-sm"><span className="text-zinc-300">{c.nome}</span><span className="text-amber-300">Vincular Meta</span></div>)}{!semMeta.length&&metaOk?<div className="rounded-2xl border border-emerald-500/15 bg-emerald-500/[.05] p-4 text-sm text-emerald-200">Nenhuma pendência crítica identificada.</div>:null}</div></div></section>
 </div></AppShell>
}