import Link from "next/link";
import { AppShell } from "@/app/components/dashboard/AppShell";
import { supabaseAdmin } from "@/app/lib/supabaseAdmin";

export const dynamic = "force-dynamic";
export const revalidate = 0;

type Etapa="novo_lead"|"qualificando"|"proposta_enviada"|"negociacao"|"fechado_ganho"|"perdido"|"numero_invalido";
type Lead={id:string;nome:string|null;telefone:string;nicho:string|null;como_chegou:string|null;etapa:Etapa;atualizado_em:string;pausado_ia:boolean};
const stageOrder:[Etapa,string][]=[["novo_lead","Novo Lead"],["qualificando","Qualificando"],["proposta_enviada","Proposta"],["negociacao","Negociação"],["fechado_ganho","Fechado"],["perdido","Perdido"]];
function days(v:string){return Math.floor((Date.now()-new Date(v).getTime())/86400000)}
function pct(v:number){return `${Math.round(v*100)}%`}

export default async function CrmExecutivoPage(){
 const {data}=await supabaseAdmin.from("leads_comerciais").select("id,nome,telefone,nicho,como_chegou,etapa,atualizado_em,pausado_ia").order("atualizado_em",{ascending:false});
 const leads=(data??[]) as Lead[];const valid=leads.filter(l=>l.etapa!=="numero_invalido");const open=valid.filter(l=>!["fechado_ganho","perdido"].includes(l.etapa));const won=valid.filter(l=>l.etapa==="fechado_ganho");const lost=valid.filter(l=>l.etapa==="perdido");const proposals=valid.filter(l=>["proposta_enviada","negociacao"].includes(l.etapa));const cold=open.filter(l=>days(l.atualizado_em)>5);const assumed=open.filter(l=>l.pausado_ia);const conversion=(won.length+lost.length)?won.length/(won.length+lost.length):0;
 const byStage=stageOrder.map(([key,label])=>({key,label,count:valid.filter(l=>l.etapa===key).length}));const maxStage=Math.max(1,...byStage.map(x=>x.count));
 const bySource=new Map<string,number>();valid.forEach(l=>{const k=(l.como_chegou||"não informado").replace(/_/g," ");bySource.set(k,(bySource.get(k)??0)+1)});const sources=[...bySource.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6);const maxSource=Math.max(1,...sources.map(([,n])=>n));
 const attention=[...cold].sort((a,b)=>days(b.atualizado_em)-days(a.atualizado_em)).slice(0,8);
 return <AppShell title="CRM" subtitle="Visão executiva do pipeline comercial" activeLabel="CRM">
  <div className="space-y-5">
   <section className="flex flex-col gap-4 rounded-[28px] border border-white/10 bg-gradient-to-br from-zinc-950 via-zinc-950 to-[#D85A30]/[.07] p-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#D85A30]">Axven CRM OS</p><h2 className="mt-2 text-2xl font-semibold text-white">Comando comercial</h2><p className="mt-2 text-sm text-zinc-400">Pipeline, conversão e oportunidades que exigem ação.</p></div><Link href="/pipeline" className="rounded-xl border border-[#D85A30]/30 bg-[#D85A30]/10 px-4 py-2 text-sm font-medium text-[#f0a480]">Abrir pipeline completo →</Link></section>
   <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Leads abertos",open.length,"Em andamento"],["Propostas",proposals.length,"Proposta + negociação"],["Ganhos",won.length,"Fechados"],["Conversão",pct(conversion),"Ganhos ÷ decisões"],["Esfriando",cold.length,"Mais de 5 dias sem atualização"]].map(([l,v,d],i)=><div key={String(l)} className={`rounded-3xl border p-5 ${i===0?"border-[#D85A30]/30 bg-[#D85A30]/10":i===4&&cold.length?"border-amber-500/20 bg-amber-500/[.06]":"border-white/10 bg-zinc-950/80"}`}><p className="text-xs uppercase tracking-[.14em] text-zinc-500">{l}</p><p className="mt-3 text-3xl font-semibold text-white">{v}</p><p className="mt-2 text-xs text-zinc-500">{d}</p></div>)}</section>
   <section className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
    <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Funil</p><h3 className="mt-1 text-lg font-semibold text-white">Distribuição por etapa</h3><div className="mt-5 space-y-4">{byStage.map(s=><div key={s.key}><div className="mb-1.5 flex justify-between text-sm"><span className="text-zinc-300">{s.label}</span><span className="text-zinc-500">{s.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.06]"><div className={`h-full rounded-full ${s.key==="fechado_ganho"?"bg-emerald-500":s.key==="perdido"?"bg-rose-500":"bg-[#D85A30]"}`} style={{width:`${s.count/maxStage*100}%`}}/></div></div>)}</div></div>
    <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Aquisição</p><h3 className="mt-1 text-lg font-semibold text-white">Origem dos leads</h3><div className="mt-5 space-y-4">{sources.map(([src,n])=><div key={src}><div className="mb-1.5 flex justify-between text-sm"><span className="capitalize text-zinc-300">{src}</span><span className="text-zinc-500">{n}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-zinc-500" style={{width:`${n/maxSource*100}%`}}/></div></div>)}{!sources.length?<p className="text-sm text-zinc-500">Sem dados de origem.</p>:null}</div></div>
   </section>
   <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
    <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Prioridades</p><h3 className="mt-1 text-lg font-semibold text-white">Leads que exigem ação</h3></div><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-zinc-400">{cold.length} sinais</span></div><div className="mt-4 space-y-2">{attention.map(l=><div key={l.id} className="flex items-center justify-between gap-3 rounded-2xl border border-amber-500/15 bg-amber-500/[.04] px-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-white">{l.nome??"Sem nome"}</p><p className="mt-1 text-xs text-zinc-500">{days(l.atualizado_em)}d sem atualização · {l.nicho||"Sem nicho"}</p></div><span className="shrink-0 rounded-full border border-amber-500/20 bg-amber-500/10 px-2.5 py-1 text-xs text-amber-200">{stageOrder.find(([k])=>k===l.etapa)?.[1]??l.etapa}</span></div>)}{!attention.length?<div className="rounded-2xl border border-emerald-500/15 bg-emerald-500/[.05] p-4 text-sm text-emerald-200">Nenhum lead esfriando neste momento.</div>:null}</div></div>
    <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Operação</p><h3 className="mt-1 text-lg font-semibold text-white">Controle do atendimento</h3><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/[.04] p-4"><p className="text-xs text-zinc-500">Assumidos por você</p><p className="mt-1 text-2xl font-semibold text-white">{assumed.length}</p></div><div className="rounded-2xl bg-white/[.04] p-4"><p className="text-xs text-zinc-500">Números inválidos</p><p className="mt-1 text-2xl font-semibold text-white">{leads.filter(l=>l.etapa==="numero_invalido").length}</p></div></div><p className="mt-4 text-sm leading-6 text-zinc-500">Drag-and-drop entre etapas, conversas e controle IA continuam no pipeline operacional.</p><Link href="/pipeline" className="mt-5 inline-flex rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-sm text-zinc-200">Gerenciar pipeline →</Link></div>
   </section>
  </div>
 </AppShell>
}