"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "../../components/dashboard/AppShell";

type Cliente = { id:string; nome:string; status_pagamento:string };
type Creative = { id:string; name?:string; status?:string; spend?:number; leads?:number; cpl?:number|null; ctr?:number|null; impressions?:number; clicks?:number };
type ClientCreative = { cliente:Cliente; items:Creative[]; error?:string };

function money(v:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:2}).format(v)}
function num(v:number){return new Intl.NumberFormat("pt-BR").format(v)}

export default function CriativosExecutivoPage(){
 const [rows,setRows]=useState<ClientCreative[]>([]); const [loading,setLoading]=useState(true); const [updated,setUpdated]=useState<string|null>(null);
 async function load(){setLoading(true);try{const r=await fetch("/api/dashboard/data",{cache:"no-store"});const d=await r.json();const ativos:Cliente[]=(d.clientes??[]).filter((c:Cliente)=>c.status_pagamento!=="cancelado");const results=await Promise.all(ativos.map(async cliente=>{try{const res=await fetch(`/api/clientes/criativos?cliente_id=${cliente.id}&status=active`,{cache:"no-store"});const data=await res.json();if(!res.ok)return{cliente,items:[],error:data?.error??"Indisponível"};return{cliente,items:data?.criativos??data?.items??[]};}catch{return{cliente,items:[],error:"Indisponível"};}}));setRows(results);setUpdated(new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}));}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const all=useMemo(()=>rows.flatMap(r=>r.items.map(i=>({...i,cliente:r.cliente}))),[rows]);
 const spend=all.reduce((s,i)=>s+Number(i.spend??0),0); const leads=all.reduce((s,i)=>s+Number(i.leads??0),0); const clicks=all.reduce((s,i)=>s+Number(i.clicks??0),0); const impressions=all.reduce((s,i)=>s+Number(i.impressions??0),0); const cpl=leads?spend/leads:null; const ctr=impressions?clicks/impressions*100:null;
 const ranked=[...all].filter(i=>Number(i.leads??0)>0).sort((a,b)=>Number(b.leads??0)-Number(a.leads??0)); const top=ranked[0];
 const clientStats=rows.map(r=>({cliente:r.cliente,count:r.items.length,spend:r.items.reduce((s,i)=>s+Number(i.spend??0),0),leads:r.items.reduce((s,i)=>s+Number(i.leads??0),0),error:r.error})).sort((a,b)=>b.spend-a.spend); const maxSpend=Math.max(1,...clientStats.map(x=>x.spend));
 return <AppShell title="Criativos" subtitle="Performance consolidada dos anúncios" activeLabel="Criativos" sidebarStatus={{lastUpdated:updated}} actions={<div className="flex gap-2"><Link href="/criativos" className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-zinc-200">Gerador IA</Link><button onClick={()=>void load()} disabled={loading} className="rounded-xl border border-[#D85A30]/30 bg-[#D85A30]/10 px-4 py-2 text-sm text-[#f0a480] disabled:opacity-50">{loading?"Atualizando...":"↻ Atualizar"}</button></div>}>
 <div className="space-y-5">
  <section className="rounded-[28px] border border-white/10 bg-gradient-to-br from-zinc-950 via-zinc-950 to-[#D85A30]/[.07] p-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#D85A30]">Axven Creative Intelligence</p><h2 className="mt-2 text-2xl font-semibold text-white">Performance criativa da carteira</h2><p className="mt-2 text-sm text-zinc-400">Leitura consolidada dos criativos ativos dos clientes conectados à Meta.</p></section>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Criativos ativos",num(all.length),`${rows.length} clientes analisados`],["Investimento",money(spend),"Criativos ativos"],["Leads",num(leads),"Resultados atribuídos"],["CPL médio",cpl==null?"—":money(cpl),"Investimento ÷ leads"],["CTR médio",ctr==null?"—":`${ctr.toFixed(2)}%`,"Cliques ÷ impressões"]].map(([l,v,d],idx)=><div key={l} className={`rounded-3xl border p-5 ${idx===0?"border-[#D85A30]/30 bg-[#D85A30]/10":"border-white/10 bg-zinc-950/80"}`}><p className="text-xs uppercase tracking-[.14em] text-zinc-500">{l}</p><p className="mt-3 text-3xl font-semibold text-white">{v}</p><p className="mt-2 text-xs text-zinc-500">{d}</p></div>)}</section>
  <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Carteira</p><h3 className="mt-1 text-lg font-semibold text-white">Investimento por cliente</h3><div className="mt-5 space-y-4">{clientStats.map(x=><div key={x.cliente.id}><div className="mb-1.5 flex items-center justify-between gap-4 text-sm"><Link href={`/clientes/${x.cliente.id}`} className="truncate text-zinc-200 hover:text-white">{x.cliente.nome}</Link><span className="shrink-0 text-zinc-400">{x.error?"—":`${money(x.spend)} · ${x.leads} leads`}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#D85A30]" style={{width:`${x.spend/maxSpend*100}%`}}/></div></div>)}{!loading&&!clientStats.length?<p className="text-sm text-zinc-500">Nenhum cliente ativo encontrado.</p>:null}</div></div>
   <div className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Destaque</p><h3 className="mt-1 text-lg font-semibold text-white">Melhor criativo por leads</h3>{top?<div className="mt-5"><p className="text-xs text-[#f0a480]">{top.cliente.nome}</p><p className="mt-2 text-xl font-semibold text-white">{top.name??"Criativo sem nome"}</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/[.04] p-4"><p className="text-xs text-zinc-500">Leads</p><p className="mt-1 text-xl font-semibold text-white">{num(Number(top.leads??0))}</p></div><div className="rounded-2xl bg-white/[.04] p-4"><p className="text-xs text-zinc-500">CPL</p><p className="mt-1 text-xl font-semibold text-white">{top.cpl==null?"—":money(Number(top.cpl))}</p></div><div className="rounded-2xl bg-white/[.04] p-4"><p className="text-xs text-zinc-500">Investimento</p><p className="mt-1 font-semibold text-white">{money(Number(top.spend??0))}</p></div><div className="rounded-2xl bg-white/[.04] p-4"><p className="text-xs text-zinc-500">CTR</p><p className="mt-1 font-semibold text-white">{top.ctr==null?"—":`${Number(top.ctr).toFixed(2)}%`}</p></div></div></div>:<p className="mt-5 text-sm text-zinc-500">Ainda não há criativos ativos com leads para destacar.</p>}</div>
  </section>
  <section className="rounded-3xl border border-white/10 bg-zinc-950/80 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Ranking</p><h3 className="mt-1 text-lg font-semibold text-white">Criativos que mais geram resultado</h3></div><span className="text-xs text-zinc-500">Somente dados disponíveis nas contas conectadas</span></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b border-white/10 text-left text-zinc-500"><tr><th className="py-3 pr-4 font-medium">Cliente</th><th className="py-3 pr-4 font-medium">Criativo</th><th className="py-3 pr-4 font-medium">Investimento</th><th className="py-3 pr-4 font-medium">Leads</th><th className="py-3 pr-4 font-medium">CPL</th><th className="py-3 font-medium">CTR</th></tr></thead><tbody className="divide-y divide-white/[.06]">{ranked.slice(0,12).map(i=><tr key={`${i.cliente.id}-${i.id}`}><td className="py-3 pr-4 text-zinc-400">{i.cliente.nome}</td><td className="py-3 pr-4 font-medium text-white">{i.name??"—"}</td><td className="py-3 pr-4 text-zinc-300">{money(Number(i.spend??0))}</td><td className="py-3 pr-4 text-white">{num(Number(i.leads??0))}</td><td className="py-3 pr-4 text-zinc-300">{i.cpl==null?"—":money(Number(i.cpl))}</td><td className="py-3 text-zinc-300">{i.ctr==null?"—":`${Number(i.ctr).toFixed(2)}%`}</td></tr>)}{!loading&&!ranked.length?<tr><td colSpan={6} className="py-8 text-center text-zinc-500">Nenhum resultado criativo disponível no momento.</td></tr>:null}</tbody></table></div></section>
 </div></AppShell>;
}
