"use client";

import { useEffect, useMemo, useRef, useState } from "react";

declare global { interface Window { fbq?: (...args: unknown[]) => void } }

type Answers = Record<string, string>;
type ResultState = null | "qualified" | "unqualified" | "error";
const trackingKeys = ["utm_source","utm_medium","utm_campaign","utm_content","utm_term","fbclid","campaign_id","adset_id","ad_id"] as const;
function captureTracking(){const params=new URLSearchParams(window.location.search);const captured:Record<string,string>={};trackingKeys.forEach(k=>{const value=params.get(k);if(value)captured[k]=value});return captured}

const questions = [
  { key:"name", label:"Qual é o seu nome?", type:"text", placeholder:"Seu nome e sobrenome" },
  { key:"whatsapp", label:"Qual é o melhor WhatsApp para falar com você?", type:"tel", placeholder:"(81) 99999-9999" },
  { key:"instagram", label:"Qual é o Instagram da sua clínica?", type:"text", placeholder:"@sua_clinica" },
  { key:"revenue", label:"Qual é o faturamento médio mensal da sua clínica?", type:"options", options:[["20","Até R$ 20 mil"],["34","R$ 20 mil a R$ 35 mil"],["60","R$ 35 mil a R$ 60 mil"],["100","R$ 60 mil a R$ 100 mil"],["300","R$ 100 mil a R$ 300 mil"],["301","Acima de R$ 300 mil"]] },
  { key:"ads", label:"Quanto sua clínica investe atualmente em anúncios por mês?", type:"options", options:[["Ainda não investimos","Ainda não investimos"],["Até R$ 1.500","Até R$ 1.500"],["R$ 1.500 a R$ 3.000","R$ 1.500 a R$ 3.000"],["R$ 3.000 a R$ 5.000","R$ 3.000 a R$ 5.000"],["R$ 5.000 a R$ 10.000","R$ 5.000 a R$ 10.000"],["Acima de R$ 10.000","Acima de R$ 10.000"]] },
  { key:"challenge", label:"Qual é o principal desafio da sua clínica hoje?", type:"options", options:[["Gerar mais oportunidades","Gerar mais oportunidades"],["Melhorar a qualidade dos leads","Melhorar a qualidade dos leads"],["Transformar mais leads em agendamentos","Transformar mais leads em agendamentos"],["Melhorar o comparecimento","Melhorar o comparecimento"],["Transformar mais agendamentos em vendas","Transformar mais agendamentos em vendas"],["Identificar onde perdemos oportunidades","Identificar onde perdemos oportunidades"],["Outro","Outro"]] },
  { key:"new_patients", label:"Em média, quantos novos pacientes entram por mês?", type:"options", options:[["0-5","Até 5"],["6-10","De 6 a 10"],["11-20","De 11 a 20"],["21-40","De 21 a 40"],["41-60","De 41 a 60"],["61+","Mais de 60"]] },
] as const;

function formatPhone(value:string){const digits=value.replace(/\D/g,"").slice(0,11);if(digits.length<=2)return digits;if(digits.length<=7)return `(${digits.slice(0,2)}) ${digits.slice(2)}`;return `(${digits.slice(0,2)}) ${digits.slice(2,7)}-${digits.slice(7)}`}
function formatInstagram(value:string){const clean=value.trim().replace(/^https?:\/\/(www\.)?instagram\.com\//i,"").replace(/^@+/,"").replace(/[^a-zA-Z0-9._]/g,"").slice(0,30);return clean?`@${clean}`:""}
function track(name:string){if(typeof window!=="undefined"&&window.fbq)window.fbq("trackCustom",name)}

export default function DiagnosticForm(){
  const [started,setStarted]=useState(false); const [step,setStep]=useState(0); const [answers,setAnswers]=useState<Answers>({}); const [sending,setSending]=useState(false); const [result,setResult]=useState<ResultState>(null); const [leadId,setLeadId]=useState<string|null>(null); const submissionId=useRef<string|null>(null);
  const question=questions[step]; const progress=started?Math.round(((step+1)/questions.length)*100):0;
  const current=answers[question?.key]||"";
  const canContinue=useMemo(()=>{if(!question)return false;if(question.key==="whatsapp")return current.replace(/\D/g,"").length===11;if(question.key==="instagram")return /^@[A-Za-z0-9._]{1,30}$/.test(current);return current.trim().length>0},[question,current]);

  function start(){setStarted(true);track("StartDiagnostic")}
  function update(value:string){if(!question)return;let next=value;if(question.key==="whatsapp")next=formatPhone(value);if(question.key==="instagram")next=formatInstagram(value);setAnswers(a=>({...a,[question.key]:next}))}
  function next(){if(!canContinue)return;if(step<questions.length-1)setStep(s=>s+1);else submit(answers)}
  function back(){if(step>0)setStep(s=>s-1)}
  function choose(value:string){if(!question)return;const nextAnswers={...answers,[question.key]:value};setAnswers(nextAnswers);if(step<questions.length-1)setTimeout(()=>setStep(s=>s+1),120);else setTimeout(()=>submit(nextAnswers),120)}
  async function submit(payload:Answers){if(sending)return;submissionId.current??=crypto.randomUUID();setSending(true);setResult(null);try{const response=await fetch("/api/aquisicao/clinicas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,submission_id:submissionId.current,...captureTracking(),origin_url:window.location.href})});if(!response.ok)throw new Error();const data=await response.json();setLeadId(data.id||null);window.fbq?.("track","Lead");if(data.qualified){track("QualifiedLead");setResult("qualified")}else setResult("unqualified")}catch{setResult("error")}finally{setSending(false)}}

  if(result==="qualified"&&leadId)return <Scheduler leadId={leadId}/>;
  if(result==="unqualified")return <Result title="Obrigado pelas informações." text="Neste momento, a Estrutura de Crescimento Axven foi desenhada para operações em uma fase específica de maturidade. Suas informações poderão ser consideradas futuramente."/>;
  if(result==="error")return <Result title="Não foi possível concluir agora." text="Tente novamente em instantes. Suas respostas não foram confirmadas." retry={()=>{setResult(null);setStep(questions.length-1)}}/>;

  if(!started)return <section className="flex flex-1 items-center py-16"><div className="w-full"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#FF6B35]">Diagnóstico Axven</p><h1 className="mt-5 text-4xl font-semibold leading-tight tracking-[-0.035em] md:text-6xl">Vamos analisar o momento atual da sua clínica.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#9B9BA4]">Responda algumas perguntas rápidas para entendermos se a Estrutura de Crescimento Axven faz sentido para sua operação.</p><button onClick={start} className="mt-9 rounded-xl bg-gradient-to-r from-[#FF6B35] to-[#FF3D57] px-7 py-4 font-semibold text-white">Começar análise →</button><p className="mt-4 text-sm text-[#686872]">Leva aproximadamente 2 minutos.</p></div></section>;

  return <section className="flex flex-1 items-center py-12"><div className="w-full"><div className="mb-10"><div className="flex items-center justify-between text-xs font-semibold uppercase tracking-[0.14em] text-[#787882]"><span>Pergunta {step+1} de {questions.length}</span><span>{progress}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#1C1C23]"><div className="h-full rounded-full bg-gradient-to-r from-[#FF6B35] to-[#FF3D57] transition-all" style={{width:`${progress}%`}}/></div></div><button onClick={back} disabled={step===0} className="mb-6 text-sm text-[#777781] disabled:invisible">← Voltar</button><h2 className="max-w-2xl text-3xl font-semibold leading-tight tracking-[-0.025em] md:text-5xl">{question.label}</h2>
    {question.type==="options"?<div className="mt-9 grid gap-3">{question.options.map(([value,label])=><button key={value} onClick={()=>choose(value)} className={`rounded-2xl border p-5 text-left text-base transition md:text-lg ${current===value?"border-[#FF6B35] bg-[#FF6B35]/10":"border-[#2A2A32] bg-[#111117] hover:border-[#4A4A54]"}`}>{label}</button>)}</div>:<div className="mt-9"><input autoFocus type={question.type==="tel"?"tel":"text"} inputMode={question.type==="tel"?"numeric":undefined} value={current} onChange={e=>update(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&canContinue)next()}} placeholder={question.placeholder} className="w-full border-b border-[#3A3A43] bg-transparent px-1 py-4 text-2xl outline-none placeholder:text-[#55555E] focus:border-[#FF6B35] md:text-3xl"/><button disabled={!canContinue||sending} onClick={next} className="mt-8 rounded-xl bg-gradient-to-r from-[#FF6B35] to-[#FF3D57] px-7 py-4 font-semibold text-white disabled:opacity-40">{sending?"Enviando...":step===questions.length-1?"Concluir análise →":"Continuar →"}</button></div>}
  </div></section>;
}

function Scheduler({leadId}:{leadId:string}){const[slots,setSlots]=useState<string[]>([]);const[loading,setLoading]=useState(true);const[booking,setBooking]=useState<string|null>(null);const[confirmed,setConfirmed]=useState<string|null>(null);const[error,setError]=useState("");useEffect(()=>{fetch("/api/aquisicao/clinicas/agenda").then(r=>r.json()).then(d=>setSlots(d.slots||[])).catch(()=>setError("Não foi possível carregar os horários.")).finally(()=>setLoading(false))},[]);async function book(inicio:string){setBooking(inicio);setError("");try{const r=await fetch("/api/aquisicao/clinicas/agenda",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leadId,inicio})});if(!r.ok)throw new Error();setConfirmed(inicio);window.fbq?.("track","Schedule")}catch{setError("Esse horário não está mais disponível. Escolha outro horário.");const r=await fetch("/api/aquisicao/clinicas/agenda");const d=await r.json();setSlots(d.slots||[])}finally{setBooking(null)}}if(confirmed){const d=new Date(confirmed);return <Result title="Análise de Crescimento agendada." text={`Seu horário foi reservado para ${d.toLocaleDateString("pt-BR",{timeZone:"America/Sao_Paulo",weekday:"long",day:"2-digit",month:"2-digit"})} às ${d.toLocaleTimeString("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit"})}.`}/>}const groups=slots.reduce<Record<string,string[]>>((a,s)=>{const k=new Date(s).toLocaleDateString("pt-BR",{timeZone:"America/Sao_Paulo",weekday:"short",day:"2-digit",month:"2-digit"});(a[k]??=[]).push(s);return a},{});return <section className="flex flex-1 items-center py-12"><div className="w-full"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#FF6B35]">Perfil compatível</p><h2 className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">Sua clínica tem perfil para avançar.</h2><p className="mt-4 text-[#9B9BA4]">Escolha um horário para sua Análise de Crescimento Axven. Duração: 45 minutos.</p>{loading&&<p className="mt-8 text-[#9B9BA4]">Carregando horários...</p>}{error&&<p className="mt-6 text-sm text-red-300">{error}</p>}<div className="mt-8 space-y-6">{Object.entries(groups).map(([day,items])=><div key={day}><p className="mb-3 font-medium capitalize">{day}</p><div className="grid grid-cols-3 gap-3 md:grid-cols-6">{items.map(s=><button key={s} disabled={!!booking} onClick={()=>book(s)} className="rounded-xl border border-[#34343D] px-3 py-3 text-sm hover:border-[#FF6B35] hover:bg-[#FF6B35]/10 disabled:opacity-50">{booking===s?"...":new Date(s).toLocaleTimeString("pt-BR",{timeZone:"America/Sao_Paulo",hour:"2-digit",minute:"2-digit"})}</button>)}</div></div>)}</div></div></section>}
function Result({title,text,retry}:{title:string;text:string;retry?:()=>void}){return <section className="flex flex-1 items-center py-16"><div className="w-full rounded-3xl border border-[#2A2A32] bg-[#111117] p-8 text-center md:p-12"><div className="mx-auto mb-5 h-2 w-16 rounded-full bg-gradient-to-r from-[#FF6B35] to-[#FF3D57]"/><h2 className="text-3xl font-semibold">{title}</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-[#9B9BA4]">{text}</p>{retry&&<button onClick={retry} className="mt-7 rounded-xl border border-[#3A3A43] px-5 py-3">Tentar novamente</button>}</div></section>}
